version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bluetrust-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blue_trust_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: node:18
    container_name: bluetrust-back
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    command: sh -c "npm install && npm run dev"

  frontend:
    image: node:18
    container_name: bluetrust-front
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

volumes:
  postgres_data:
